<?php namespace App;

/**
 * Eloquent class to describe the articles table
 *
 * automatically generated by ModelGenerator.php
 */
class Articles extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'articles';

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('title', 'body', 'created_by', 'deleted_at');

}

