<?php namespace App;

/**
 * Eloquent class to describe the cron_job table
 *
 * automatically generated by ModelGenerator.php
 */
class CronJob extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cron_job';

    public $timestamps = false;

    protected $fillable = array('name', 'return', 'runtime', 'cron_manager_id');

}

