<?php namespace App;

/**
 * Eloquent class to describe the cron_manager table
 *
 * automatically generated by ModelGenerator.php
 */
class CronManager extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cron_manager';

    public $timestamps = false;

    public function getDates()
    {
        return array('rundate');
    }

    protected $fillable = array('rundate', 'runtime');

}

