<?php namespace App;

/**
 * Eloquent class to describe the intervention_image table
 *
 * automatically generated by ModelGenerator.php
 */
class InterventionImage extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'intervention_image';

    protected $fillable = array('title', 'images', 'base64_images');

}

