<?php namespace App;

/**
 * Eloquent class to describe the jobs table
 *
 * automatically generated by ModelGenerator.php
 */
class Jobs extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'jobs';

    protected $fillable = array('queue', 'payload', 'attempts', 'reserved', 'reserved_at', 'available_at');

}

