<?php namespace App;

/**
 * Eloquent class to describe the permissions table
 *
 * automatically generated by ModelGenerator.php
 */
class Permissions extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'permissions';

    protected $fillable = array('name');

    public function roless()
    {
        return $this->belongsToMany('App\Roles', 'role_has_permissions', 'role_id', 'permission_id');
    }

    public function userss()
    {
        return $this->belongsToMany('App\Users', 'user_has_permissions', 'user_id', 'permission_id');
    }

}

