<?php namespace App;

/**
 * Eloquent class to describe the users table
 *
 * automatically generated by ModelGenerator.php
 */
class Users extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'users';

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('name', 'email', 'password', 'remember_token', 'deleted_at');

    public function permissionss()
    {
        return $this->belongsToMany('App\Permissions', 'user_has_permissions', 'permission_id', 'user_id');
    }

    public function roless()
    {
        return $this->belongsToMany('App\Roles', 'user_has_roles', 'role_id', 'user_id');
    }

}

