<?php namespace App;

/**
 * Eloquent class to describe the wp_comments table
 *
 * automatically generated by ModelGenerator.php
 */
class WpComments extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'wp_comments';

    public $primaryKey = 'comment_ID';

    public $timestamps = false;

    public function getDates()
    {
        return array('comment_date', 'comment_date_gmt');
    }

    protected $fillable = array('comment_post_ID', 'comment_author', 'comment_author_email', 'comment_author_url',
        'comment_author_IP', 'comment_date', 'comment_date_gmt', 'comment_content', 'comment_karma', 'comment_approved',
        'comment_agent', 'comment_type', 'comment_parent', 'user_id');

}

