<?php namespace App;

/**
 * Eloquent class to describe the wp_options table
 *
 * automatically generated by ModelGenerator.php
 */
class WpOptions extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'wp_options';

    public $primaryKey = 'option_id';

    public $timestamps = false;

    protected $fillable = array('option_name', 'option_value', 'autoload');

}

