<?php namespace App;

/**
 * Eloquent class to describe the wp_postmeta table
 *
 * automatically generated by ModelGenerator.php
 */
class WpPostmeta extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'wp_postmeta';

    public $primaryKey = 'meta_id';

    public $timestamps = false;

    protected $fillable = array('post_id', 'meta_key', 'meta_value');

}

