<?php namespace App;

/**
 * Eloquent class to describe the wp_terms table
 *
 * automatically generated by ModelGenerator.php
 */
class WpTerms extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'wp_terms';

    public $primaryKey = 'term_id';

    public $timestamps = false;

    protected $fillable = array('name', 'slug', 'term_group');

}

