<?php namespace App;

/**
 * Eloquent class to describe the wp_term_taxonomy table
 *
 * automatically generated by ModelGenerator.php
 */
class WpTermTaxonomy extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'wp_term_taxonomy';

    public $primaryKey = 'term_taxonomy_id';

    public $timestamps = false;

    protected $fillable = array('term_id', 'taxonomy', 'description', 'parent', 'count');

}

