<?php namespace App;

/**
 * Eloquent class to describe the wp_users table
 *
 * automatically generated by ModelGenerator.php
 */
class WpUsers extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'wp_users';

    public $primaryKey = 'ID';

    public $timestamps = false;

    public function getDates()
    {
        return array('user_registered');
    }

    protected $fillable = array('user_login', 'user_pass', 'user_nicename', 'user_email', 'user_url', 'user_registered',
        'user_activation_key', 'user_status', 'display_name');

}

