<?php namespace App;

/**
 * Eloquent class to describe the wp_usermeta table
 *
 * automatically generated by ModelGenerator.php
 */
class WpUsermeta extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'wp_usermeta';

    public $primaryKey = 'umeta_id';

    public $timestamps = false;

    protected $fillable = array('user_id', 'meta_key', 'meta_value');

}

